### PR TITLE
Document minimum Go version of 1.10.0.

### PR DESCRIPTION
**Pull request by JeremyRand**
TODO:

- [x] Merge https://github.com/namecoin/crosssignnameconstraint/pull/3

### CODE REVIEW

**Comment by JeremyRand** [comment]
Ready for review.

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/tlsrestrictnss/pull/11/commits/56ff83675add4edb62f5f9f8b30f52c4dc73485e

**Comment by JeremyRand** [comment]
That should fix the Travis fail for this PR (which isn't actually caused by this PR...).

**Comment by hlandau** [comment]
ACK https://github.com/namecoin/tlsrestrictnss/pull/11/commits/7bf00e3317be83893ed8e61c6267fcaa826978b0

**Pull request merged**
